const PDFDocument = require('pdfkit');

/**
 * Generates a Health Summary PDF for a user
 * @param {Object} userData - User info (name, etc)
 * @param {Array} logs - Array of DailyLog documents
 * @returns {Promise<Buffer>} - Resovles with PDF buffer
 */
const generateHealthReport = (userData, logs) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            let buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                let pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            // Header
            doc.fillColor('#2563eb')
                .fontSize(25)
                .text('SympoCare Health Report', { align: 'center' });

            doc.moveDown();
            doc.fillColor('#4b5563')
                .fontSize(12)
                .text(`Report Generated For: ${userData.name}`, { align: 'left' });
            doc.text(`Date Range: ${logs.length > 0 ? logs[0].date.toDateString() : 'N/A'} - ${new Date().toDateString()}`);

            doc.moveDown();
            doc.path('M 50,150 L 550,150').stroke(); // Horizontal line
            doc.moveDown();

            // Summary Section
            doc.fillColor('#1f2937').fontSize(18).text('Executive Summary', { underline: true });
            doc.moveDown(0.5);

            const totalLogs = logs.length;
            const avgScore = totalLogs > 0 ? (logs.reduce((acc, l) => acc + l.dailyScore, 0) / totalLogs).toFixed(1) : 0;
            const avgSleep = totalLogs > 0 ? (logs.reduce((acc, l) => acc + l.sleepHours, 0) / totalLogs).toFixed(1) : 0;

            doc.fontSize(12).text(`Total Check-ins: ${totalLogs}`);
            doc.text(`Average Wellness Score: ${avgScore}/10`);
            doc.text(`Average Sleep: ${avgSleep} hours`);

            doc.moveDown();

            // Daily Details Table
            doc.fillColor('#1f2937').fontSize(18).text('Recent Activity Log', { underline: true });
            doc.moveDown(0.5);

            // Table Header
            const startX = 50;
            const rowHeight = 25;
            let currentY = doc.y;

            doc.fontSize(10).fillColor('#6b7280');
            doc.text('Date', startX, currentY);
            doc.text('Score', startX + 100, currentY);
            doc.text('Sleep', startX + 180, currentY);
            doc.text('Water', startX + 260, currentY);
            doc.text('Mood', startX + 340, currentY);

            currentY += rowHeight;
            doc.path(`M ${startX},${currentY - 5} L 550,${currentY - 5}`).stroke('#e5e7eb');

            // Table Rows
            doc.fillColor('#374151');
            logs.slice(0, 15).forEach(log => {
                if (currentY > 700) {
                    doc.addPage();
                    currentY = 50;
                }
                doc.text(log.date.toLocaleDateString(), startX, currentY);
                doc.text(`${log.dailyScore}/10`, startX + 100, currentY);
                doc.text(`${log.sleepHours}h`, startX + 180, currentY);
                doc.text(`${log.waterIntake}L`, startX + 260, currentY);
                doc.text(log.mood || 'N/A', startX + 340, currentY);

                currentY += rowHeight;
            });

            // Disclaimer
            doc.moveDown();
            doc.fillColor('#ef4444')
                .fontSize(10)
                .text('DISCLAIMER: This report is generated by an automated system and is for informational purposes only. It is not a clinical diagnosis. Please consult a healthcare professional for medical advice.', { align: 'center' });

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
};

module.exports = { generateHealthReport };
